### PR TITLE
fixed bug in iframe shortcode when using additional parameters

### PR DESCRIPTION
**Pull request by Kephson**
fixed bug in iframe shortcode when using additional parameters, see #19 
updated gitignore file

### CODE REVIEW

**Comment by mikestreety** [comment]
Of course, thanks for the PR. Would you mind removing the `.gitignore` changes please as they are separate to the issue?

Thanks

**Comment by Kephson** [comment]
Hi, yes I deleted the .gitignore file from this pull request

**Comment by mikestreety** [comment]
Thanks @Kephson - I did mean undo the changes you added, but don't worry, I can handle it :)

**Comment by mikestreety** [comment]
Closing this as it is now on a local branch

https://github.com/liquidlight/typo3-shortcodes/pull/22

**Pull request closed without merging**
